In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

### 1. Ordinal Encoding

In [9]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4], df.iloc[:,-1], test_size=0.2)

In [30]:
X_train.head(5)

     review education
39     Poor        PG
21  Average        PG
8   Average        UG
18     Good    School
47     Good        PG

In [31]:
# specify order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [32]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

In [20]:
X_train

array([[0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [1., 1.]])

In [33]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [34]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [35]:
oe.n_features_in_

2

In [36]:
oe.inverse_transform(np.array([0,2]).reshape(1,2))

array([['Poor', 'PG']], dtype=object)

In [41]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [42]:
# handle unknown
oe.transform(np.array(['Poor','college']).reshape(1,2))

d:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('college')] in column 1 during transform

In [46]:
# set unknown value
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4], df.iloc[:,-1], test_size=0.2)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

d:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

In [47]:
# handling infrequent categories
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [48]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [49]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [51]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [1.],
       [2.],
       [2.],
       [2.]])

In [52]:
enc = OrdinalEncoder(min_frequency=4).fit(X)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [53]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

In [54]:
# handling missing data

# Example categorical data with missing values
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]

# Setting encoded_missing_value to -1, indicating we want missing values to be encoded as -1
encoder = OrdinalEncoder(encoded_missing_value=-1)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [ 2.]
 [-1.]]

### LabelEncoder

In [55]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [56]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [57]:
from sklearn.preprocessing import LabelEncoder

In [58]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [59]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [60]:
le.inverse_transform(np.array([1,1,0]))

array(['Yes', 'Yes', 'No'], dtype=object)

### 2. OneHotEncoder

In [150]:
cars = pd.read_csv('cars.csv')
cars.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [151]:
cars.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [152]:
X = cars.iloc[:,0:3].drop(columns=['km_driven'])
y = cars.iloc[:,-1]

In [165]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [166]:
X_train['fuel'].nunique()

4

In [167]:
from sklearn.preprocessing import OneHotEncoder

In [168]:
ohe = OneHotEncoder(sparse_output=False, dtype=np.int32)

In [169]:
X_train = ohe.fit_transform(X_train)
X_train

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], shape=(6502, 36), dtype=int32)

In [170]:
X_train.shape

(6502, 36)

In [171]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [172]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [173]:
ohe.n_features_in_

2

In [174]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [175]:
pd.DataFrame(X_train,columns=ohe.get_feature_names_out())

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# form dataframe again if required

In [177]:
ohe.inverse_transform(np.array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1.]).reshape(1,36))

array([['Audi', 'Petrol']], dtype=object)

In [178]:
# drop
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train).shape

(6502, 34)

In [179]:
ohe.drop_idx_

array([0, 0], dtype=object)

In [180]:
# handling rare categories
X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [181]:
cars['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [182]:
# using min frequency

ohe = OneHotEncoder(sparse_output=False, min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [183]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

In [184]:
# using max_categories
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', max_categories=15)
ohe.fit_transform(X_train).shape

(6502, 19)

In [185]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Jaguar', 'brand_Mahindra', 'brand_Maruti',
       'brand_Nissan', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_CNG', 'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [186]:
# how to handle unknown category
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

d:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('local')] in column 0 during transform

In [187]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

d:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [188]:
ohe.inverse_transform(np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]).reshape(1,36))

array([[None, 'Petrol']], dtype=object)

### LabelBinarizer

In [189]:
from sklearn.preprocessing import LabelBinarizer

# Sample target variable for a multi-class classification problem
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize the LabelBinarizer
lb = LabelBinarizer()

# Fit and transform the target variable
y_binarized = lb.fit_transform(y)

print("Binarized labels:\n", y_binarized)

# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)

print("Original labels:\n", y_original)

Binarized labels:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels:
 ['cat' 'dog' 'fish' 'dog' 'cat']

In [190]:
from sklearn.preprocessing import MultiLabelBinarizer

# Example multi-label data
y = [('red', 'blue'), ('blue', 'green'), ('green',), ('red',)]

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the data to binary matrix format
Y = mlb.fit_transform(y)

print("Binary matrix:\n", Y)
print("Class labels:", mlb.classes_)

# Inverse transform to recover original labels
y_inv = mlb.inverse_transform(Y)
print("Inverse transformed labels:", y_inv)

Binary matrix:
 [[1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]]
Class labels: ['blue' 'green' 'red']
Inverse transformed labels: [('blue', 'red'), ('blue', 'green'), ('green',), ('red',)]

### 3. Count Encoder/Frequency Encoder

In [1]:
!pip install category_encoders

Requirement already satisfied: category_encoders in D:\anaconda\Lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in D:\anaconda\Lib\site-packages (from category_encoders) (2.4.6)
Requirement already satisfied: pandas>=1.0.5 in D:\anaconda\Lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in D:\anaconda\Lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in D:\anaconda\Lib\site-packages (from category_encoders) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in D:\anaconda\Lib\site-packages (from category_encoders) (1.17.1)
Requirement already satisfied: statsmodels>=0.9.0 in D:\anaconda\Lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\anaconda\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in D:\anaconda\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in D:\anaconda\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: six>=1.5 in D:\anaconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in D:\anaconda\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in D:\anaconda\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (2.22.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in D:\anaconda\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in D:\anaconda\Lib\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)

In [4]:
# dataset generation
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

df = pd.DataFrame(data)

df.head()

    Age        State    Education    Package
0  29.0  Maharashtra           UG  46.343044
1  22.0   Tamil Nadu           UG  49.609695
2   NaN        Delhi  High School  45.503101
3  26.0    Telangana  High School   7.252160
4  34.0    Telangana  High School  14.693563

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Package']), df['Package'], test_size=0.2, random_state=42)

In [6]:
X_train.head()

     Age        State    Education
55   NaN    Telangana  High School
88  34.0   Tamil Nadu  High School
26   NaN    Telangana           UG
42  36.0  Maharashtra           PG
69  40.0    Karnataka           PG

In [7]:
X_train['State'].value_counts()

State
Delhi          21
Maharashtra    18
Karnataka      15
Tamil Nadu     14
Telangana      12
Name: count, dtype: int64

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import sklearn

In [10]:
class CountEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, columns=None):
        self.columns = columns
        self.count_map = {}

    def fit(self, X, y=None):
        if self.columns is None:
            self.columns = X.columns
        for col in self.columns:
            self.count_map[col] = X[col].value_counts().to_dict()
        return self

    def transform(self, X):
        X = X.copy()
        for col in self.columns:
            X[col] = X[col].map(self.count_map[col]).fillna(0)
        return X

In [11]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])

sklearn.set_config(transform_output="pandas")

In [12]:
preprocessor.fit_transform(X_train)

    age_missing__Age  cat_state__State  education_ordinal__Education
55             38.08                12                           1.0
88             35.00                18                           0.0
26             38.08                15                           2.0
42             34.00                15                           0.0
69             57.00                18                           1.0
..               ...               ...                           ...
60             51.00                18                           0.0
71             20.00                11                           1.0
14             49.00                24                           2.0
92             36.00                18                           2.0
51             56.00                15                           0.0

[80 rows x 3 columns]

In [2]:
# using category encoders
from category_encoders.count import CountEncoder

In [15]:
X_train

     Age        State    Education
55   NaN    Telangana  High School
88  34.0   Tamil Nadu  High School
26   NaN    Telangana           UG
42  36.0  Maharashtra           PG
69  40.0    Karnataka           PG
..   ...          ...          ...
60  24.0  Maharashtra  High School
71  48.0  Maharashtra           UG
14  41.0        Delhi           PG
92  55.0   Tamil Nadu           UG
51  53.0  Maharashtra           PG

[80 rows x 3 columns]

In [10]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(normalize=True), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])

In [16]:
X_train =preprocessor.fit_transform(X_train)

In [17]:
pd.DataFrame(X_train,columns=preprocessor.get_feature_names_out())

    age_missing__Age  cat_state__State  education_ordinal__Education
0          38.106667            0.1500                           0.0
1          34.000000            0.1750                           0.0
2          38.106667            0.1500                           2.0
3          36.000000            0.2250                           1.0
4          40.000000            0.1875                           1.0
..               ...               ...                           ...
75         24.000000            0.2250                           0.0
76         48.000000            0.2250                           2.0
77         41.000000            0.2625                           1.0
78         55.000000            0.1750                           2.0
79         53.000000            0.2250                           1.0

[80 rows x 3 columns]

In [ ]:
# frequency encoding

In [39]:
# parameters
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
np.random.seed(42)  # For reproducibility
data = {
    'State': np.random.choice(np.array(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana', np.nan],dtype=object), size=100),
    'Education': np.random.choice(np.array(['High School', 'UG', 'PG', np.nan],dtype=object), size=100)
}
df = pd.DataFrame(data)


df.head(25)

          State    Education
0         Delhi           PG
1     Telangana  High School
2   Maharashtra  High School
3     Telangana  High School
4     Telangana           PG
5    Tamil Nadu  High School
6   Maharashtra          NaN
7   Maharashtra  High School
8   Maharashtra          NaN
9     Telangana          NaN
10        Delhi          NaN
11  Maharashtra           PG
12          NaN           PG
13    Telangana           PG
14   Tamil Nadu  High School
15        Delhi          NaN
16          NaN           PG
17          NaN           PG
18   Tamil Nadu  High School
19        Delhi           PG
20    Telangana  High School
21    Karnataka           UG
22        Delhi           PG
23   Tamil Nadu           UG
24          NaN  High School

In [40]:
df.isnull().sum()

State        17
Education    23
dtype: int64

In [41]:
# Initialize the CountEncoder with various parameters
encoder = ce.CountEncoder(
    cols=['State', 'Education'],  # Specify columns to encode. None would automatically select categorical columns.
    handle_missing='error',  # Treat NaNs as a non-countable category
    handle_unknown='error',  # Treat unknown categories as non-countable category
)

In [30]:
# Fit and transform the dataset
encoder.fit_transform(df)

#print(encoded_df.head(25))

ValueError: Columns to be encoded can not contain null

In [31]:
encoder.mapping

In [32]:
new_data = pd.DataFrame({'State': ['Bihar'], 'Education': ['UG']})

encoder.transform(new_data)

TypeError: 'NoneType' object is not subscriptable

In [43]:
np.random.seed(0)  # For reproducibility
data = {
    'Category': np.random.choice(np.array(['A', 'B', 'C', 'D', 'E', 'F', np.nan], dtype=object), size=100, p=[0.3, 0.25, 0.15, 0.15, 0.05, 0.05, 0.05]),
    'Value': np.random.rand(100)
}

df = pd.DataFrame(data)


df.sample(10)

   Category     Value
91        C  0.209844
29        B  0.290078
2         C  0.735194
50        C  0.149448
44        C  0.806194
78        A  0.704414
33        C  0.298282
65        B  0.855803
75        A  0.223925
45        C  0.703889

In [44]:
df['Category'].value_counts()

Category
A    34
B    22
C    21
D    12
F     4
E     2
Name: count, dtype: int64

In [45]:
df.isnull().sum()

Category    5
Value       0
dtype: int64

In [46]:
encoder = ce.CountEncoder(
    cols=['Category'],
    min_group_size=10,  # Groups with counts less than 5 will be combined
    min_group_name='salman',  # Use default naming for combined minimum groups
)

# Fit and transform the dataset
encoded_df = encoder.fit_transform(df['Category'])

# Display the original and encoded data for comparison
df['Encoded'] = encoded_df
print(df.head(20))

   Category     Value  Encoded
0         B  0.677817       22
1         D  0.270008       12
2         C  0.735194       21
3         B  0.962189       22
4         B  0.248753       22
5         C  0.576157       21
6         B  0.592042       22
7         E  0.572252       11
8       NaN  0.223082       11
9         B  0.952749       22
10        D  0.447125       12
11        B  0.846409       22
12        C  0.699479       21
13        F  0.297437       11
14        A  0.813798       34
15        A  0.396506       34
16        A  0.881103       34
17        D  0.581273       12
18        D  0.881735       12
19        E  0.692532       11

In [47]:
encoder.mapping

{'Category': Category
 A         34
 B         22
 C         21
 D         12
 salman    11
 Name: count, dtype: int64}

### Binary Encoder

In [48]:
import pandas as pd
import category_encoders as ce

# Sample dataset
data = {
    'Item': ['Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8'],
    'Fruit': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry', 'Fig', 'Grape', 'Honeydew']
}
df = pd.DataFrame(data)

df

    Item       Fruit
0  Item1       Apple
1  Item2      Banana
2  Item3      Cherry
3  Item4        Date
4  Item5  Elderberry
5  Item6         Fig
6  Item7       Grape
7  Item8    Honeydew

In [49]:
# Initialize the Binary Encoder
encoder = ce.BinaryEncoder(cols=['Fruit'], return_df=True)

# Fit and transform the data
df_encoded = encoder.fit_transform(df)

# Display the original and encoded data
print(df_encoded)

    Item  Fruit_0  Fruit_1  Fruit_2  Fruit_3
0  Item1        0        0        0        1
1  Item2        0        0        1        0
2  Item3        0        0        1        1
3  Item4        0        1        0        0
4  Item5        0        1        0        1
5  Item6        0        1        1        0
6  Item7        0        1        1        1
7  Item8        1        0        0        0

### Target Encoder

In [50]:
# using category_encoder

import pandas as pd
import category_encoders as ce

# Sample data
data = {
    'Feature': ['A', 'B', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Target': [1, 0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

# Separating the feature and target columns
X = df.drop('Target', axis=1)
y = df['Target']

# Initialize the TargetEncoder
encoder = ce.TargetEncoder(cols=['Feature'])

# Fit the encoder using the feature data and target variable
encoder.fit(X, y)

# Transform the data
encoded = encoder.transform(X)

# Show the original and encoded data
print(pd.concat([df, encoded], axis=1))

  Feature  Target   Feature
0       A       1  0.631436
1       B       0  0.579948
2       A       0  0.631436
3       B       1  0.579948
4       C       1  0.678194
5       A       1  0.631436
6       B       0  0.579948
7       C       1  0.678194

In [51]:
encoder.mapping

{'Feature': Feature
  1    0.631436
  2    0.579948
  3    0.678194
 -1    0.625000
 -2    0.625000
 dtype: float64}

In [52]:
# using sklearn
import pandas as pd
from sklearn.preprocessing import TargetEncoder

# Sample data
data = {
    'Feature': ['A', 'B', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Target': [1, 0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

# Separating the feature and target columns
X = df.drop('Target', axis=1)
y = df['Target']

# Initialize the TargetEncoder
encoder = TargetEncoder(smooth=0.0)

# Fit the encoder using the feature data and target variable
encoder.fit(X, y)

# Transform the data
encoded = encoder.transform(X)

encoded

array([[0.66666667],
       [0.33333333],
       [0.66666667],
       [0.33333333],
       [1.        ],
       [0.66666667],
       [0.33333333],
       [1.        ]])

### Weight of Evidence

In [ ]:
import pandas as pd
import category_encoders as ce

# Example dataset
data = {
    'Feature': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Target': [1, 0, 0, 1, 1, 0, 1, 0, 1, 0]
}
df = pd.DataFrame(data)

# Define the features and target
X = df[['Feature']]
y = df['Target']

# Initialize and fit the TargetEncoder
encoder = ce.WOEEncoder(cols=['Feature'])
X_encoded = encoder.fit_transform(X, y)   # regularization=1.0 is applied

# Display the original and encoded data  
df['Feature_Encoded'] = X_encoded
print(df)

  Feature  Target  Feature_Encoded
0       A       1         0.000000
1       B       0        -0.405465
2       A       0         0.000000
3       C       1         0.405465
4       B       1        -0.405465
5       A       0         0.000000
6       C       1         0.405465
7       B       0        -0.405465
8       A       1         0.000000
9       C       0         0.405465